<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Audit Logs Report - TriadCo</title>
    <style>
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        body {
            font-family: 'DejaVu Sans', sans-serif;
            font-size: 11px;
            color: #333;
            line-height: 1.4;
        }
        .header {
            text-align: center;
            padding: 20px 0;
            border-bottom: 3px solid #1e2a47;
            margin-bottom: 20px;
        }
        .header h1 {
            color: #1e2a47;
            font-size: 24px;
            margin-bottom: 5px;
        }
        .header p {
            color: #666;
            font-size: 12px;
        }
        .meta-info {
            background: #f8f9fa;
            padding: 15px;
            border-radius: 8px;
            margin-bottom: 20px;
        }
        .meta-row {
            display: flex;
            justify-content: space-between;
            margin-bottom: 8px;
        }
        .meta-label {
            font-weight: bold;
            color: #1e2a47;
        }
        .stats-grid {
            display: table;
            width: 100%;
            margin-bottom: 20px;
        }
        .stat-box {
            display: table-cell;
            width: 25%;
            text-align: center;
            padding: 15px;
            background: #f8f9fa;
            border: 1px solid #dee2e6;
        }
        .stat-box h3 {
            font-size: 22px;
            color: #1e2a47;
            margin-bottom: 5px;
        }
        .stat-box p {
            color: #6c757d;
            font-size: 10px;
            text-transform: uppercase;
        }
        table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 15px;
        }
        th {
            background: #1e2a47;
            color: #fff;
            padding: 10px 8px;
            text-align: left;
            font-size: 10px;
            text-transform: uppercase;
        }
        td {
            padding: 8px;
            border-bottom: 1px solid #dee2e6;
            font-size: 10px;
        }
        tr:nth-child(even) {
            background: #f8f9fa;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            padding-top: 15px;
            border-top: 1px solid #dee2e6;
            color: #6c757d;
            font-size: 10px;
        }
        .section-title {
            color: #1e2a47;
            font-size: 14px;
            margin: 20px 0 10px 0;
            padding-bottom: 5px;
            border-bottom: 2px solid #c8a858;
        }
        .badge {
            display: inline-block;
            padding: 2px 8px;
            border-radius: 10px;
            font-size: 9px;
            font-weight: bold;
        }
        .filter-info {
            background: #e8f4f8;
            padding: 10px;
            border-radius: 5px;
            margin-bottom: 15px;
            font-size: 10px;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>TRIAD CO. HOTEL</h1>
        <p>Audit Logs Report</p>
    </div>

    <div class="meta-info">
        <table style="width: 100%; border: none;">
            <tr>
                <td style="border: none; padding: 5px;"><strong>Generated:</strong> {{ now()->format('F d, Y h:i A') }}</td>
                <td style="border: none; padding: 5px;"><strong>Generated By:</strong> {{ auth()->user()->name ?? 'System' }}</td>
            </tr>
            <tr>
                <td style="border: none; padding: 5px;"><strong>Filter:</strong> {{ ucfirst($filter ?? 'All Logs') }}</td>
                <td style="border: none; padding: 5px;"><strong>Total Records:</strong> {{ $reports->count() }}</td>
            </tr>
            @if($dateFrom || $dateTo)
            <tr>
                <td colspan="2" style="border: none; padding: 5px;">
                    <strong>Date Range:</strong> {{ $dateFrom ?? 'Beginning' }} to {{ $dateTo ?? 'Present' }}
                </td>
            </tr>
            @endif
        </table>
    </div>

    <div class="stats-grid">
        <div class="stat-box">
            <h3>{{ $stats['totalActivities'] }}</h3>
            <p>Total Activities</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['totalItems'] }}</h3>
            <p>Total Items</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['totalSuppliers'] }}</h3>
            <p>Total Suppliers</p>
        </div>
        <div class="stat-box">
            <h3>{{ $stats['totalRooms'] }}</h3>
            <p>Total Rooms</p>
        </div>
    </div>

    <h3 class="section-title">Activity Log Details</h3>
    
    <table>
        <thead>
            <tr>
                <th style="width: 8%;">#</th>
                <th style="width: 50%;">Activity</th>
                <th style="width: 20%;">User</th>
                <th style="width: 22%;">Date & Time</th>
            </tr>
        </thead>
        <tbody>
            @forelse($reports as $index => $report)
                <tr>
                    <td>{{ $index + 1 }}</td>
                    <td>{{ $report->activity }}</td>
                    <td>{{ $report->user ? $report->user->name : 'Unknown' }}</td>
                    <td>{{ $report->created_at->format('M d, Y h:i A') }}</td>
                </tr>
            @empty
                <tr>
                    <td colspan="4" style="text-align: center; padding: 20px;">No records found</td>
                </tr>
            @endforelse
        </tbody>
    </table>

    <div class="footer">
        <p>&copy; {{ date('Y') }} TriadCo Hotel Management System. All rights reserved.</p>
        <p>This is a system-generated report. For internal use only.</p>
    </div>
</body>
</html>
